### ISSUE TITLE
Add Microphone Activity Status

### ISSUE THREAD

**Issue by fedmog1lnkv** [FlorianButz/DynamicWin#1]
The current version of DynamicWin lacks a visual indicator for microphone activity, which would help users see when their microphone is actively capturing sound. I propose adding this feature similar to Discord, where an indicator lights up or changes color when the audio level exceeds a certain dB threshold.

**Functional Requirements:**

1. **Microphone Activity Indicator:**
   - Implement a visual indicator (e.g., LED or animation) that lights up or changes color when the microphone picks up sound above a specified dB threshold.

2. **Threshold Settings:**
   - Provide users with the ability to adjust the microphone activity threshold through the program's settings, allowing them to set the dB level at which the indicator activates.

**Comment by FlorianButz** [comment]
I can look in to that, thanks for the suggestion

**Comment by FlorianButz** [comment]
The feature will come in version 1.0.2r which I will probably release later this day.
