### ISSUE TITLE
screen alignment and mouse bugs

### ISSUE THREAD

**Issue by MiktatMertCento** [FlorianButz/DynamicWin#11]
Hey buddy, the project is awesome—I really loved it! But there’s a problem with the screen alignment, just like in the video attached. Also, the mouse positions are all off. Could you please fix this ASAP so we can use?

pc type is laptop
screen res: 1920x1080
screen scale: 125%
text size: 100%

[youtube video](https://youtu.be/hMN2lA2jM1w)

**Comment by FlorianButz** [comment]
I will work on a solution as soon as possible. I first need to try if I can recreate this bug, thanks for the information attached.

**Comment by FlorianButz** [comment]
Will be fixed in 1.0.5R.
