### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by AdriRed** [FlorianButz/DynamicWin#14]
Hi! I'm compiling and adapting the code for ARM machines (take a look at my fork!, I'm removing the COMReference and doing a ComImport instead). 

I suposed that you were using Inno Setup, but since I'm new to this tool I'm getting an error because Windows Defender is flagging the temp file as trojan...

I would like (and for new contributors) to see a build guide!

**Comment by AdriRed** [comment]
Just compiled with `iscc.exe` and removing the false positive of windows defender.

**Comment by AdriRed** [comment]
In case that you need, commands are:

`dotnet build -c Release`

`iscc .\Other\DynamicWinSetupProject.iss`

You may have to adapt for the folder structure that you have, I'm editing the iss for being relative instead of absolute.

**Comment by FlorianButz** [comment]
Thanks. I was planing to add a build batch file anyway. I was alseep, so I wasn‘t available.
