### ISSUE TITLE
add try catch around LibreMonitor calls that might fail

### ISSUE THREAD

**Issue by ToolmakerSteve** [FlorianButz/DynamicWin#17]
HardwareMonitor.Timer_Elapsed:

ln. 40  
`computer.Open();`  
internally got NullReference Exception.

Can't do remaining code in that case.

It's running on a timer, so the exception doesn't stop the rest of the app.  
But it is cleaner coding to catch it. If only to show a line in Visual Studio Output, when debugging the app.

**Comment by FlorianButz** [comment]
The Computer instance is now created before the timer is started. A null reference exception should be excluded now
