### ISSUE TITLE
Spotify closed to system tray

### ISSUE THREAD

**Issue by LifeDreamer24** [FlorianButz/DynamicWin#28]
Amazing project! I love it and it fits so well with [this one](https://github.com/PlayForm/Round).
However, I am used to close Spotify when done choosing a song, but it simply displays "Error - Spotify is not open!" when activating the option to hide to system tray upon closing the window...

![image](https://github.com/user-attachments/assets/90f90d31-9bfd-436a-9016-272a9aa57df9)

![image](https://github.com/user-attachments/assets/9ebdc821-6cb3-4ee2-acb9-11097651c30c)

Thanks again for making the Dynamic Island available on Windows! <3

**Comment by FlorianButz** [comment]
Due to the way the media player works this cannot be fixed. It would require me to use the windows media player interface which is sadly not available for my app.
