### ISSUE TITLE
dynamic island not centered + not opening

### ISSUE THREAD

**Issue by GuiltySpen** [FlorianButz/DynamicWin#3]
won't open to view music and settings etc cant drag and drop files

https://github.com/user-attachments/assets/e54e53dc-5613-4564-8dba-201f467b4f72

**Comment by FlorianButz** [comment]
Do you know what screen resolution you have?

**Comment by GuiltySpen** [comment]
hi ive discovered and fixed the issue by changing the size of text and apps to 100 from 150 then back to 150

**Comment by MiktatMertCento** [comment]
> hi ive discovered and fixed the issue by changing the size of text and apps to 100 from 150 then back to 150
same but not working 

my screen settings:
![image](https://github.com/user-attachments/assets/2198cdc4-708d-45ee-a68b-255af53cf1e8)
