### ISSUE TITLE
Handle different screen resolutions

### ISSUE THREAD

**Issue by TwentyFourMinutes** [FlorianButz/DynamicWin#6]
Hey, first and foremost, you did an awesome job and I really like the idea of the App!

I am using a 4k Display and it seems that the App always expects to be rendered on a 1080p Display:
![image](https://github.com/user-attachments/assets/c501d03b-e07e-4371-aadf-b17dd56c6fc3)

Here are a few suggestions that IMO the app could really benefit from:
- Scaling
  - [ ] Adjust the scaling of the app accordingly to the screen size. 
- Positioning of the window
  - [ ] Always center the window regardless of the screen size.
 
If I can assist you in any way, feel free to let me know :)

**Comment by FlorianButz** [comment]
The problem is that when I test it on a different resolution everything seems to work fine.
I think there is an issue with the actual hardware and it doesn't seem to mind when I artificially increase the resolution on nvidia control panel.
I'll take a look at it.

**Comment by FlorianButz** [comment]
I tried it out on my system and after starting the app it automatically adjusts to the screen resolution. I'm not sure what the problem is here, but I can't seem to find the issue. If you have an idea on how to fix this, I'd be happy to receive your help. You can see if the version v1.0.3R fixes it for you (will release later today).

**Comment by TwentyFourMinutes** [comment]
@FlorianButz I'll give it a shot after the update. Thank you so much, appreciate the work 😄

**Comment by TwentyFourMinutes** [comment]
@FlorianButz I installed the most recent version and on my 4k display everything works as intended. Nice work!
