### ISSUE TITLE
Handle multiple displays

### ISSUE THREAD

**Issue by TwentyFourMinutes** [FlorianButz/DynamicWin#7]
From what I could tell, the App currently always renders on my Laptop Screen and not the external screens. It would be nice if it could handle the following scenarios:

- Listening to the primary display setting from the Windows Setting Menu. 
  - [ ] Window always renders on the primary display.
  <img width="895" alt="image" src="https://github.com/user-attachments/assets/a6de70a7-e7d3-4734-9f82-5ad67fe0985e">
- Automatically adjust to displays being added/removed.
  - [ ] If the primary display gets unplugged choose the next best one available.  

If I can assist you in any way, feel free to let me know :)

**Comment by FlorianButz** [comment]
I already tried doing that before release but didn't get to it. I'll take a look at it and see what I can do

**Comment by FlorianButz** [comment]
This will be added in v1.0.3R. You'll then be able to select the monitor of your choice and it automatically updates when it gets disconnected.
