### ISSUE TITLE
[BUG] Crashes if no devices are connected

### ISSUE THREAD

**Issue by DerekGooding** [FlorianButz/DynamicWin#8]

**Comment by FlorianButz** [comment]
Can you provide a list of steps needed to re-produce this issue? With devices, are you referring to microphone/camera or something else?

**Comment by DerekGooding** [comment]
Certainly. Listening devices. If I don't have a speaker or headphones active, it crashes on line 

defaultDevice = devEnum.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);

in app.OnStartup. 

Likely just needs a handler.

**Comment by FlorianButz** [comment]
Should be fixed in v1.0.3R
