### ISSUE TITLE
[BUG] Opening settings too quickly hard locks the application

### ISSUE THREAD

**Issue by DerekGooding** [FlorianButz/DynamicWin#9]
If you open the app and immediately navigate to settings, the entire island is blurred and there is no option to cancel.

**Comment by FlorianButz** [comment]
I think this issue was fixed after I updated the menu animation which will be in v1.0.3R. I can't recreate the issue, as I am too slow. If the bug still persists, you can re-open the issue.

**Comment by DerekGooding** [comment]
Correction, this isn't a hard lock. Although the menu is blurry, you can still hover over and click Apply and Back. So for anyone having that issue, there is a workaround.
